### ISSUE TITLE
index.ts writeJsonFile을 fp스럽게 만들어주셨으면 조케씁니다

### ISSUE THREAD

**Issue by zusinShinpei** [ByeongGi/ng-builder-markdown#1]
tap((_) => writeJsonFile(outputPath, _)) <<<< 를
tap(writeJsonFile(outputPath)) 이렇게

**Comment by ByeongGi** [comment]
fp 스타일스럽게 전반적인 스타일을 변경을 해야겠네요.
의견 참고해서 refator 할때 최대한 반영해보겠습니다.
